### ISSUE TITLE
error in: Compute quality of eigenvectors

### ISSUE THREAD

**Issue by stephanschulz** [natalialmg/IR_iHR#2]
Thank you again for posting your code.
I am slowly learning more about python to run parts of it.
I got the face mask stuff working :)

But I get the bellow error message when running iHR_extraction. 
I converted iHR_extraction.ipynb to .py and run it like so `python3 /IR_iHR-master/iHR_extraction.py`

When it comes to accessing https://github.com/natalialmg/IR_iHR/blob/71ae747d741411a0daa633b922381bdee438c954/iHR_utils.py#L117
the below error appears.
Would you know why?
I am using your `sample_data.pkl` file also.

```
Traceback (most recent call last):
  File "/IR_iHR-master/iHR_extraction.py", line 108, in <module>
    quality_array = iHR_utils.quality_process(V[0:nv,:],prior_bpm,fs,
  File "/IR_iHR-master/iHR_utils.py", line 129, in quality_process
    stft_v, f_v,_,_= sq.SST_helper(filtered_signal, fs, fH/fs, fL/fs, windowLength=window)
  File "/IR_iHR-master/sq_stft_utils.py", line 237, in SST_helper
    tfr, tfrtic, tfrsq, tfrsqtic = SST_STFT(x, lowFreq, highFreq, FrequencyAxisResolution, h, Dh, 1,
  File "/IR_iHR-master/sq_stft_utils.py", line 66, in SST_STFT
    tfrtic = np.linspace(0, 0.5, N/2)
  File "<__array_function__ internals>", line 5, in linspace
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/function_base.py", line 113, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer
```
Thanks for any advice.

**Comment by natalialmg** [comment]
Hi Stephan,
I apologize I did not see this message earlier. I think the issue there is that in linspace you need to cast N/2 to integer as: np.linspace(0, 0.5, int(N/2)). You are probably working with another python version that does not do it automatically. Best.

**Comment by Kavyasnairmtech** [comment]
Thank you for the code.
Can you please provide the full  dataset?
It will be more helpful for me.

**Comment by whr1241** [comment]
I also meet the similar problems,could you have a look about my issue?

IndexError                                Traceback (most recent call last)
<ipython-input-22-419dcf74e9be> in <module>
      9 quality_array = iHR_utils.quality_process(V[0:nv,:],prior_bpm,fs,
     10                                 window = window,fL=fL,fH = fH,
---> 11                                 fp_d = fp_d,fp_u = fp_u)

D:\1maydaystudy\1PycharmProjects\Reproduction\IR_iHR-master\iHR_utils.py in quality_process(signals, prior_bpm, fs, window, fL, fH, fp_d, fp_u, verbose)
    132         t_v = np.arange(filtered_signal.shape[0])/fs
    133 
--> 134         stft_v, f_v,_,_= sq.SST_helper(filtered_signal, fs, fH//fs, fL//fs, windowLength=window)  # 这个函数有问题？
    135 
    136         f_v = f_v*fs

D:\1maydaystudy\1PycharmProjects\Reproduction\IR_iHR-master\sq_stft_utils.py in SST_helper(x, Hz, highFreq, lowFreq, windowLength)
    241     FrequencyAxisResolution = 0.001
    242     h, Dh = hermf(windowLength, 1, 2)
--> 243     tfr, tfrtic, tfrsq, tfrsqtic = SST_STFT(x, lowFreq, highFreq, FrequencyAxisResolution, h, Dh, 1, False, False)
    244 
    245     return tfr, tfrtic, tfrsq, tfrsqtic

D:\1maydaystudy\1PycharmProjects\Reproduction\IR_iHR-master\sq_stft_utils.py in SST_STFT(x, lowFreq, highFreq, alpha, h, Dh, tDS, Smooth, Hemi)
     83 
     84     Mid = np.round(tfrsqtic.size/2).astype('int')
---> 85     Delta = 20*(tfrsqtic[2]-tfrsqtic[1])**2  # **代表幂运算 index 2 is out of bounds for axis 0 with size 0 有什么问题？
     86     weight = np.exp(-(tfrsqtic[Mid-10:Mid+10]-tfrsqtic[Mid])**2/Delta)
     87     weight = weight / sum(weight)

IndexError: index 2 is out of bounds for axis 0 with size 0

**Comment by whr1241** [comment]
> Thank you again for posting your code.
> I am slowly learning more about python to run parts of it.
> I got the face mask stuff working :)
> 
> But I get the bellow error message when running iHR_extraction.
> I converted iHR_extraction.ipynb to .py and run it like so `python3 /IR_iHR-master/iHR_extraction.py`
> 
> When it comes to accessing
> 
> https://github.com/natalialmg/IR_iHR/blob/71ae747d741411a0daa633b922381bdee438c954/iHR_utils.py#L117
> 
> 
> the below error appears.
> Would you know why?
> I am using your `sample_data.pkl` file also.
> ```
> Traceback (most recent call last):
>   File "/IR_iHR-master/iHR_extraction.py", line 108, in <module>
>     quality_array = iHR_utils.quality_process(V[0:nv,:],prior_bpm,fs,
>   File "/IR_iHR-master/iHR_utils.py", line 129, in quality_process
>     stft_v, f_v,_,_= sq.SST_helper(filtered_signal, fs, fH/fs, fL/fs, windowLength=window)
>   File "/IR_iHR-master/sq_stft_utils.py", line 237, in SST_helper
>     tfr, tfrtic, tfrsq, tfrsqtic = SST_STFT(x, lowFreq, highFreq, FrequencyAxisResolution, h, Dh, 1,
>   File "/IR_iHR-master/sq_stft_utils.py", line 66, in SST_STFT
>     tfrtic = np.linspace(0, 0.5, N/2)
>   File "<__array_function__ internals>", line 5, in linspace
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/function_base.py", line 113, in linspace
>     num = operator.index(num)
> TypeError: 'float' object cannot be interpreted as an integer
> ```
> 
> Thanks for any advice.

I met the same problem, could you tell me how to solve it?

**Comment by whr1241** [comment]
![Uploading image.png…]()

**Comment by whr1241** [comment]
![image](https://user-images.githubusercontent.com/62423115/120881436-99a71e80-c603-11eb-8607-11c38aca22ed.png)

**Comment by natalialmg** [comment]
Sorry for the late response. 

The first error in 'np.linspace(0, 0.5, N/2)' I think is due to N/2 that in recent versions of python need to be casted to int (np.linspace(0, 0.5, int(N/2))). The other one is just a warning, the code was developed on a earlier version of python 3.X.
